version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_support_system
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql  # Gắn dữ liệu vào thư mục mysql_data trong dự án
      - ./mysql_utf8.cnf:/etc/mysql/conf.d/mysql_utf8.cnf  # Mount config UTF-8

  # backend:
  #   build: .
  #   container_name: express_backend
  #   restart: always
  #   depends_on:
  #     - mysql
  #   environment:
  #     PORT: 5000
  #     DB_HOST: mysql
  #     DB_USER: user
  #     DB_PASSWORD: userpassword
  #     DB_NAME: student_support_system
  #     DB_PORT: 3306
  #     JWT_SECRET: super_secret_key_here
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/app
  #   command: ["node", "server.js"]

volumes:
  mysql_data:
